name: Doc
on: [push, pull_request]

env:
  FORCE_COLOR: "1"
  PRE_COMMIT_COLOR: "always"
  # See https://github.com/theacodes/nox/issues/545
  # and https://github.com/pre-commit/pre-commit/issues/2178#issuecomment-1002163763
  SETUPTOOLS_USE_DISTUTILS: "stdlib"
jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install
        run: |
          pip install invoke d2py
          pip install .
      - name: Set up environment
        uses: ./.github/actions/setup
      # - name: Conda Build
      #   shell: cmd /C call {0}
      #   run: >-
      #     conda build --output-folder=conda/pkg conda/recipe &&
      #     conda install tvm -c ./conda/pkg
      - name: Docs
        run: 
          cd docs
          make html


      - name: 🚀 Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/html/
